# _**Creating DataFrames**_
---
- Let’s look at different ways to create a Pandas DataFrame — the core data structure you’ll be using 90% of the time in data science.

In [1]:
import pandas as pd , numpy as np

## From Python Lists

In [8]:
data = [
    ["Priyam" , 65],
    ["Gary" , 98],
    ["Ash" , 87]
]
df = pd.DataFrame(data , columns=('Name','Marks') , index = range(1,4)) # Added custom index and column's name
df

     Name  Marks
1  Priyam     65
2    Gary     98
3     Ash     87

## From Dictionary of lists
- Most common and readable format.
- Each key becomes a column, and each list is the column data.

In [9]:
data = {
"Name": ["Alice", "Bob", "Charlie"],
"Age": [25, 30, 35]
}
df = pd.DataFrame(data)
df

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

## From NumPy Arrays
----

In [12]:
arr = np.array([[1, 2], [3, 4]])
df = pd.DataFrame(arr)
df

   0  1
0  1  2
1  3  4

# From CSV(Comma Seprated Values) Files
---

## 1. sep

- Specifies the delimiter used in the file.

In [17]:
df = pd.read_csv("data.csv",sep=',')
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

## 2. header

- Specifies which row contains the column names.

In [21]:
df = pd.read_csv("data.csv",header=1)
df

,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
0,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
1,Aamir Khan,Dangal,2016,Biography,2024,8.4
2,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
3,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
4,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
5,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
6,Hrithik Roshan,War,2019,Action,475,6.5
7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
8,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
9,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
10,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

## 3. names

- Provide your own column names.

In [24]:
df= pd.read_csv(
    "data.csv",
    # header=None , <--------- doesn't matter
    names=['Names','Movies','Time','Type','Collection','Rating']
)
df

,Names,Movies,Time,Type,Collection,Rating
0,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
1,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
3,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
5,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
6,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
7,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
8,Hrithik Roshan,War,2019,Action,475,6.5
9,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
12,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

## 4. index_col

- Choose which column becomes the index.

In [26]:
df = pd.read_csv("data.csv", index_col="Film")
df

,Actor,Year,Genre,BoxOffice(INR Crore),IMDb
Film,,,,,
Pathaan,Shah Rukh Khan,2023,Action,1050,7.2
Tiger Zinda Hai,Salman Khan,2017,Action,565,6.0
Dangal,Aamir Khan,2016,Biography,2024,8.4
Brahmastra,Ranbir Kapoor,2022,Fantasy,431,5.6
Padmaavat,Ranveer Singh,2018,Historical,585,7.0
Andhadhun,Ayushmann Khurrana,2018,Thriller,111,8.3
Stree,Rajkummar Rao,2018,Horror Comedy,180,7.5
War,Hrithik Roshan,2019,Action,475,6.5
Good Newwz,Akshay Kumar,2019,Comedy,318,7.0
Bhool Bhulaiyaa 2,Kartik Aaryan,2022,Horror Comedy,266,5.9
Badrinath Ki Dulhania,Varun Dhawan,2017,Romantic Comedy,201,6.1
Uri: The Surgical Strike,Vicky Kaushal,2019,Action,342,8.2

# 5. usecols

- Read only selected columns.

In [35]:
# df = pd.read_csv("data.csv", usecols=["Actor","Film"])
df = pd.read_csv("data.csv", usecols=[0,1])  #<-------------------------------- Above one and this one works same

df

                 Actor                      Film
0       Shah Rukh Khan                   Pathaan
1          Salman Khan           Tiger Zinda Hai
2           Aamir Khan                    Dangal
3        Ranbir Kapoor                Brahmastra
4        Ranveer Singh                 Padmaavat
5   Ayushmann Khurrana                 Andhadhun
6        Rajkummar Rao                     Stree
7       Hrithik Roshan                       War
8         Akshay Kumar                Good Newwz
9        Kartik Aaryan         Bhool Bhulaiyaa 2
10        Varun Dhawan     Badrinath Ki Dulhania
11       Vicky Kaushal  Uri: The Surgical Strike

## _**Some more options**_
--
- nrows	Read    first n rows
- skiprows	    Skip initial rows
- dtype	Set     data types
- na_values	    Handle missing values
- parse_dates	Convert date columns

# From Excel Files
---

In [38]:
df= pd.read_excel("students_data.xlsx")
df

    ID     Name  Age       City  Marks
0  101    Alice   25      Delhi     88
1  102      Bob   30     Mumbai     92
2  103  Charlie   22  Bangalore     81
3  104    David   28    Chennai     75
4  105      Eva   24     Jaipur     95

# From JSON
---
- Can also read from a URL or string.

In [39]:
df = pd.read_json("students_data.json")
df

    ID     Name  Age       City  Marks
0  101    Alice   25      Delhi     88
1  102      Bob   30     Mumbai     92
2  103  Charlie   22  Bangalore     81
3  104    David   28    Chennai     75
4  105      Eva   24     Jaipur     95

# From the Web (Example: CSV from URL)
---

In [40]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

# _**EDA (Exploratory Data Analysis)**_
- It involves taking a deep look at the dataset to understand its structure, spot patterns, identify anomalies, and uncover relationships between variables.

## Why do EDA?

Suppose you receive a dataset with 10,000 rows.

Before analyzing it, you should know:

   -  How many rows and columns are there?

   -  Are there missing values?

   - Are there duplicate rows?

   - What are the data types?

   - Are there outliers?

   - What are the relationships between columns?

__That's what EDA helps you discover.__

In [42]:
df.head() #shows first 5 rows

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [43]:
df.tail() # shows last 5 rows

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [44]:
df.shape # (rows, columns)

(244, 7)

In [45]:
df.columns #List of columns name

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [46]:
df.info() # Column info: types, non-nulls

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [47]:
df.describe() #Stats of numeric columns

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000