# **_Data Selection & Filtering_**

- Selecting the right rows and columns is the first step in analyzing any dataset.
- Pandas gives you several powerful ways to do this.
---
## Selecting Rows & Columns

In [1]:
import pandas as pd

In [35]:
df = pd.read_csv("data.csv")

In [3]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

## Selecting Rows & Columns

In [4]:
df["Actor"]

0         Shah Rukh Khan
1            Salman Khan
2             Aamir Khan
3          Ranbir Kapoor
4          Ranveer Singh
5     Ayushmann Khurrana
6          Rajkummar Rao
7         Hrithik Roshan
8           Akshay Kumar
9          Kartik Aaryan
10          Varun Dhawan
11         Vicky Kaushal
Name: Actor, dtype: object

In [8]:
df[["Actor","Year"]]

                 Actor  Year
0       Shah Rukh Khan  2023
1          Salman Khan  2017
2           Aamir Khan  2016
3        Ranbir Kapoor  2022
4        Ranveer Singh  2018
5   Ayushmann Khurrana  2018
6        Rajkummar Rao  2018
7       Hrithik Roshan  2019
8         Akshay Kumar  2019
9        Kartik Aaryan  2022
10        Varun Dhawan  2017
11       Vicky Kaushal  2019

## Selecting Rows by index and labels

In [13]:
df.loc[[1,2,3]] # use index's lable

           Actor             Film  Year      Genre  BoxOffice(INR Crore)  IMDb
1    Salman Khan  Tiger Zinda Hai  2017     Action                   565   6.0
2     Aamir Khan           Dangal  2016  Biography                  2024   8.4
3  Ranbir Kapoor       Brahmastra  2022    Fantasy                   431   5.6

In [15]:
df.iloc[0] # use index

Actor                   Shah Rukh Khan
Film                           Pathaan
Year                              2023
Genre                           Action
BoxOffice(INR Crore)              1050
IMDb                               7.2
Name: 0, dtype: object

### Slicing

In [17]:
df.loc[0:2 , ["Actor",'IMDb']]

            Actor  IMDb
0  Shah Rukh Khan   7.2
1     Salman Khan   6.0
2      Aamir Khan   8.4

In [19]:
df.iloc[0:3,[0,5]]

            Actor  IMDb
0  Shah Rukh Khan   7.2
1     Salman Khan   6.0
2      Aamir Khan   8.4

## Note
- loc includes the ending label 
```
    df.loc[0:2 <-- (here 2 is included) ,["Actor","IMDb"]]
```
- iloc excludes the ending position
```
    df.iloc[0:3 <-- (here 3 is excluded) ,[0,5]]
```

## Fast Access: .at and .iat
---
-These are optimized for single element access:

In [20]:
df.at[0, "Actor"]# Fast label-based access

'Shah Rukh Khan'

In [22]:
df.iat[0, 1]# Fast position-based access

'Pathaan'

## Filtering with Conditions
---
- Simple Condition

In [23]:
df[df['IMDb'] >7]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

- Multiple Conditions (AND / OR)

In [25]:
df[(df['IMDb'] > 7) & (df['Genre'] == 'Action')]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [26]:
df[(df['IMDb'] > 7) | (df['Genre'] == 'Action')]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

> Use parentheses around each condition!

## ***Querying with .query()***
---
The .query() method in pandas lets you filter DataFrame rows using a string expression — it’s a more readable and often more concise alternative to using boolean indexing.

In [28]:
df.query("Year > 2018 and IMDb > 6")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [32]:
# Dynamic column names:
col = 'BoxOffice(INR Crore)'
df.query(f"`{col}` > 500")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0

```
1. Column names become variables.
    You can reference column names directly in the query string.
    
2. String values must be in quotes.
    Use single or double quotes around strings in the expression.
    
3. Use backticks for column names with spaces or special characters.
    If a column name has spaces, use backticks ( ` ).
    
4. You can use @ to reference Python variables.
    To pass external variables into .query()
    
5. Logical operators
    Use these: - and , or , not — instead of & , | , ~ - == , != , < , > , <= , >=
    Bad:
    df.query("age > 30 & city == 'Delhi'") # ❌
    Good:
    df.query("age > 30 and city == 'Delhi'") # ✅
    
7. Chained comparisons
    Just like Python.
    
8. Avoid using reserved keywords as column names
    If you have a column named class , lambda , etc., you’ll need to use backticks.

9. Case-sensitive
    Column names and string values are case-sensitive.

10. .query() returns a copy, not a view
    The result is a new DataFrame. Changes won’t affect the original unless reassigned.
```

In [43]:
df.columns.values[0]

'Name'

In [42]:
df

,Name,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2