# Data Cleaning & Preprocessing
---
Real-world data is messy. Pandas gives us powerful tools to clean and transform
data before analysis.

### Handling Missing Values
---
Check for Missing Data

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data-cleaning-sample.csv")

In [3]:
df

      Name   Age         City Gender              Email Join Date Join Date.1
0    Alice  25.0     New York      F  alice@example.com  05-01-21    05-01-21
1  Charlie   NaN        Delhi      M    charlie@example  07-20-21    07-20-21
2      Bob  30.0  Los Angeles      M    bob@example.com  06-15-20    06-15-20
3  Charlie   NaN        Delhi      M    charlie@example  07-20-21    07-20-21
4    David  22.0       Mumbai      M  david@example.com  11-12-19    11-12-19
5      NaN  28.0        Delhi      F     eve@domain.com       NaN         NaN
6    Alice  25.0     New York      F  alice@example.com  05-01-21    05-01-21
7    Alice  25.0     New York      F  alice@example.com  05-01-21    05-01-21
8  Charlie   NaN        Delhi      M    charlie@example  07-20-21    07-20-21

In [4]:
df.isnull() # Prints True for NaNs

    Name    Age   City  Gender  Email  Join Date  Join Date.1
0  False  False  False   False  False      False        False
1  False   True  False   False  False      False        False
2  False  False  False   False  False      False        False
3  False   True  False   False  False      False        False
4  False  False  False   False  False      False        False
5   True  False  False   False  False       True         True
6  False  False  False   False  False      False        False
7  False  False  False   False  False      False        False
8  False   True  False   False  False      False        False

In [5]:
df.isnull().sum() # count missing per column

Name           1
Age            3
City           0
Gender         0
Email          0
Join Date      1
Join Date.1    1
dtype: int64

### Drop missing data

In [6]:
df.dropna() # drop all the rows which have any missing values

    Name   Age         City Gender              Email Join Date Join Date.1
0  Alice  25.0     New York      F  alice@example.com  05-01-21    05-01-21
2    Bob  30.0  Los Angeles      M    bob@example.com  06-15-20    06-15-20
4  David  22.0       Mumbai      M  david@example.com  11-12-19    11-12-19
6  Alice  25.0     New York      F  alice@example.com  05-01-21    05-01-21
7  Alice  25.0     New York      F  alice@example.com  05-01-21    05-01-21

In [7]:
df.dropna(axis=1) # drop all the columns which have any missing values

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

### Fill Missing Data
- In pandas, fillna is used to fill unknown values. ffill and bfill are methods used to fill missing values (like NaN, None, or pd.NA) by propagating values forward or backward.

In [8]:
df.fillna(0) # fills 0 in place of all missing values

      Name   Age         City Gender              Email Join Date Join Date.1
0    Alice  25.0     New York      F  alice@example.com  05-01-21    05-01-21
1  Charlie   0.0        Delhi      M    charlie@example  07-20-21    07-20-21
2      Bob  30.0  Los Angeles      M    bob@example.com  06-15-20    06-15-20
3  Charlie   0.0        Delhi      M    charlie@example  07-20-21    07-20-21
4    David  22.0       Mumbai      M  david@example.com  11-12-19    11-12-19
5        0  28.0        Delhi      F     eve@domain.com         0           0
6    Alice  25.0     New York      F  alice@example.com  05-01-21    05-01-21
7    Alice  25.0     New York      F  alice@example.com  05-01-21    05-01-21
8  Charlie   0.0        Delhi      M    charlie@example  07-20-21    07-20-21

In [9]:
df["Age"].fillna(df["Age"].mean()).astype("int32") # Replace with mean also I changed it's datatype using .astype()

0    25
1    25
2    30
3    25
4    22
5    28
6    25
7    25
8    25
Name: Age, dtype: int32

In [10]:
df["Name"].ffill() # Forward fill > fill the previous value before the missing value

0      Alice
1    Charlie
2        Bob
3    Charlie
4      David
5      David
6      Alice
7      Alice
8    Charlie
Name: Name, dtype: object

In [11]:
df["Name"].bfill() # Backward fill > starts from last element and fill the next value to the missing value

0      Alice
1    Charlie
2        Bob
3    Charlie
4      David
5      Alice
6      Alice
7      Alice
8    Charlie
Name: Name, dtype: object

### Detecting & Removing Duplicates

In [12]:
df.duplicated() # Returns True for a duplicate **ROWS**

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [13]:
df.drop_duplicates() # Remove duplicate **ROWS**

      Name   Age         City Gender              Email Join Date Join Date.1
0    Alice  25.0     New York      F  alice@example.com  05-01-21    05-01-21
1  Charlie   NaN        Delhi      M    charlie@example  07-20-21    07-20-21
2      Bob  30.0  Los Angeles      M    bob@example.com  06-15-20    06-15-20
4    David  22.0       Mumbai      M  david@example.com  11-12-19    11-12-19
5      NaN  28.0        Delhi      F     eve@domain.com       NaN         NaN

In [14]:
df[["Name","Age"]].duplicated() # checks based on specific column
df.duplicated(subset=["Name", "Age"]) # Check based on specific column

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

## df.duplicated(subset=["Name", "Age"])
```
Method is called on the entire DataFrame.

Pandas internally considers only the "Name" and "Age" columns while checking for duplicate rows.

It returns a Series of booleans.
```
---

## df[["Name", "Age"]].duplicated()
```
Here:

    df[["Name", "Age"]] creates a new DataFrame object containing only those columns.

    .duplicated() is then called on that new DataFrame.

It also returns a Series of booleans
```

## String Operations with .str
---
- Works like vectorized string methods and returns a pandas Series.
- We can always chain methods like .str.strip().str.upper() for clean-up.

In [15]:
df["Name"].str.lower()

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: object

In [16]:
df["City"].str.contains("delhi",case= False)

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

In [17]:
df["Email"].str.split("@") # Outputs a pandas Series where each element is a listof strings (the split parts). This is where a Python list comes into play, but theouter object is still a pandas Series.

0    [alice, example.com]
1      [charlie, example]
2      [bob, example.com]
3      [charlie, example]
4    [david, example.com]
5       [eve, domain.com]
6    [alice, example.com]
7    [alice, example.com]
8      [charlie, example]
Name: Email, dtype: object

## Type Conversions with .astype()
---

In [18]:
df2 = df.dropna().copy()
df2["Age"] = df2["Age"].astype(int)

In [19]:
df2

    Name  Age         City Gender              Email Join Date Join Date.1
0  Alice   25     New York      F  alice@example.com  05-01-21    05-01-21
2    Bob   30  Los Angeles      M    bob@example.com  06-15-20    06-15-20
4  David   22       Mumbai      M  david@example.com  11-12-19    11-12-19
6  Alice   25     New York      F  alice@example.com  05-01-21    05-01-21
7  Alice   25     New York      F  alice@example.com  05-01-21    05-01-21

## df2["Date"] = pd.to_datetime(df2["Date"])
---
- it sorted date as datatype = datetime64[ns] instead of strings
### benefits :
- df["Date"].dt.year (Extract the year )
- df["Date"].dt.month ,df["Date"].dt.day (same with month, date)
- df[df["Date"] > "2026-07-02"] (Filtering)
- df["Date"].max() - df["Date"].min() (differnce between dates)

## df["Category"] = df["Category"].astype("category")
---
- it stores data as category instead of strings.

### Benefits

- Categories:
0 -> Food
1 -> Travel
2 -> Shopping

- Data:
0
1
0
0
2
1 instead of (food , travel , food , food , shopping , travel)


- it gives a value to each category . so it easy to access

- Sorting > (df["Category"].sort_values())

- Grouping > (df.groupby("Category").sum())

# Applying Functions
---

## .apply() → Apply any function to rows or columns

## .map() → Element-wise mapping for Series

## .replace() → Replace specific values

In [20]:
df2["Age Group"] = df2["Age"].apply(lambda x : "adult" if x > 26 else "minor")

In [21]:
df2

,Name,Age,City,Gender,Email,Join Date,Join Date.1,Age Group
0,Alice,25,New York,F,alice@example.com,05-01-21,05-01-21,minor
2,Bob,30,Los Angeles,M,bob@example.com,06-15-20,06-15-20,adult
4,David,22,Mumbai,M,david@example.com,11-12-19,11-12-19,minor
6,Alice,25,New York,F,alice@example.com,05-01-21,05-01-21,minor
7,Alice,25,New York,F,alice@example.com,05-01-21,05-01-21,minor

In [22]:
gender_map = {"M" : "Male" , "F":"Female"}
df2["Gender"] = df2["Gender"].map(gender_map)

In [23]:
df2

,Name,Age,City,Gender,Email,Join Date,Join Date.1,Age Group
0,Alice,25,New York,Female,alice@example.com,05-01-21,05-01-21,minor
2,Bob,30,Los Angeles,Male,bob@example.com,06-15-20,06-15-20,adult
4,David,22,Mumbai,Male,david@example.com,11-12-19,11-12-19,minor
6,Alice,25,New York,Female,alice@example.com,05-01-21,05-01-21,minor
7,Alice,25,New York,Female,alice@example.com,05-01-21,05-01-21,minor

In [24]:
replace_val = {"Mumbai" : "New Mumbai" , "New York" : "NYC"}
df2["City"] = df2["City"].replace(replace_val)

In [25]:
df2

,Name,Age,City,Gender,Email,Join Date,Join Date.1,Age Group
0,Alice,25,NYC,Female,alice@example.com,05-01-21,05-01-21,minor
2,Bob,30,Los Angeles,Male,bob@example.com,06-15-20,06-15-20,adult
4,David,22,New Mumbai,Male,david@example.com,11-12-19,11-12-19,minor
6,Alice,25,NYC,Female,alice@example.com,05-01-21,05-01-21,minor
7,Alice,25,NYC,Female,alice@example.com,05-01-21,05-01-21,minor

In [27]:
df2.T.duplicated()

Name           False
Age            False
City           False
Gender         False
Email          False
Join Date      False
Join Date.1     True
Age Group      False
dtype: bool

In [36]:
# to remove duplicated columns
df2 = df.loc[:, ~df.T.duplicated()] # selected all rows and columns where the value is true , and for join date 1 the value is false

In [37]:
df2

      Name   Age         City Gender              Email Join Date
0    Alice  25.0     New York      F  alice@example.com  05-01-21
1  Charlie   NaN        Delhi      M    charlie@example  07-20-21
2      Bob  30.0  Los Angeles      M    bob@example.com  06-15-20
3  Charlie   NaN        Delhi      M    charlie@example  07-20-21
4    David  22.0       Mumbai      M  david@example.com  11-12-19
5      NaN  28.0        Delhi      F     eve@domain.com       NaN
6    Alice  25.0     New York      F  alice@example.com  05-01-21
7    Alice  25.0     New York      F  alice@example.com  05-01-21
8  Charlie   NaN        Delhi      M    charlie@example  07-20-21