# Reshaping Data using Melt and Pivot
---
## melt() — Wide to Long
- The melt() method in Pandas is used to unpivot a DataFrame from wide format to long format.

### Parameters:
```
• id_vars : The columns that you want to keep fixed (these columns will remain as identifiers).
• value_vars : The columns you want to unpivot (the ones you want to “melt” into a single column).
• var_name : The name to use for the new column that will contain the names of the melted columns (default is 'variable' ).
• value_name : The name to use for the new column that will contain the values from the melted columns (default is 'value' ).
• col_level : Used for multi-level column DataFrames.
```

In [6]:
import pandas as pd

In [14]:
data = {
'Name': ['Alice', 'Bob', 'Charlie'],
'Math': [85, 78, 92],
'Science': [90, 82, 89],
'English': [88, 85, 94]
}
df = pd.DataFrame(data)
df

      Name  Math  Science  English
0    Alice    85       90       88
1      Bob    78       82       85
2  Charlie    92       89       94

In [15]:
df = df.melt(id_vars='Name',value_vars=['Math','Science','English'],var_name='Subjects',value_name='Score')
df

      Name Subjects  Score
0    Alice     Math     85
1      Bob     Math     78
2  Charlie     Math     92
3    Alice  Science     90
4      Bob  Science     82
5  Charlie  Science     89
6    Alice  English     88
7      Bob  English     85
8  Charlie  English     94

## pivot() — Long to Wide
---
The pivot() function in Pandas is used to reshape data, specifically to turn long-format data into wide-format data. This is the reverse operation of melt() .

### How it works:
```
• pivot() takes a long-format DataFrame and turns it into a wide-format DataFrame by specifying which columns will become the new columns, the rows, and the values.
```

### Parameters:
```
• index : The column whose unique values will become the rows of the new DataFrame.
• columns : The column whose unique values will become the columns of the new DataFrame.
• values : The column whose values will fill the new DataFrame. These will become the actual data (values in the table).
```

In [16]:
df = df.pivot(index='Name',columns='Subjects',values='Score')
df

Subjects  English  Math  Science
Name
Alice          88    85       90
Bob            85    78       82
Charlie        94    92       89

Duplicate Entries: If you have multiple rows with the same combination of index and columns , pivot() will raise an error. In such cases, you should use pivot_table() (which can handle duplicate entries by aggregating them).
use ***aggfunc= "mean"*** 
- df.pivot_table(index="Name", columns="Subject", values="Score", aggfunc="mean")